version: '3'
services:
  central:
    build:
      context: ./central-app
      dockerfile: Dockerfile.central
    ports:
      - "7110:7110"
    volumes:
      - ./central-app:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - session-net

  # worker:
  #   build:
  #     context: ./node-app
  #     dockerfile: Dockerfile.worker
  #   ports:
  #     - "8110:8110"
  #   volumes:
  #     - ./node-app:/app
  #   networks:
  #     - session-net

networks:
  session-net:
    driver: bridge
