version: '3.8'

services:
  central:
    build:
      context: ./central-app
      dockerfile: Dockerfile.central
    ports:
      - "7110:7110"
    volumes:
      - ./central-app:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Docker API access from the container
    networks:
      - abc-net
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=7110

networks:
  abc-net:
    driver: bridge
    external: true
