name: Deploy to EC2 on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 51.20.78.225 > ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        rsync -avz --exclude '.git*' --delete ./ ec2-user@51.20.78.225:/home/ec2-user/downloads
        ssh ec2-user@51.20.78.225 "cd /home/ec2-user/downloads && ./deploy_script.sh"
